[package]
name = "antegen-submitter"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
description = "Antegen transaction submitter with TPU client support"

[dependencies]
solana-sdk = { workspace = true }
solana-client = { workspace = true }
solana-quic-client = { workspace = true }
solana-tpu-client = { workspace = true }
solana-program = { workspace = true }

tokio = { workspace = true, features = ["sync", "rt", "time", "macros"] }
log = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-nats = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
solana-cron = { workspace = true }
antegen-thread-program = { workspace = true }
antegen-utils = { workspace = true }
anchor-lang = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }